version: '3'
services:
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/weather-challenge
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "4000:80"
